name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18] #, 20]
        firebird: ["3"] #, "4", "5"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Setup FirebirdSQL container
        uses: juarezr/firebirdsql-github-action@v2.0.0
        with:
          version: ${{ matrix.firebird }}
          firebird_root_password: "masterkey"
          firebird_conf: "WireCrypt=Enabled"
          port: 3050
          #enable_legacy_client_auth: "true"

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        shell: bash
        run: |
          npm ci

      - name: Test (Linux)
        run: |
          export FIREBIRD_DATA=/var/lib/firebird/data
          npx nyc npm test -- ./test/index.js
